<a href="https://colab.research.google.com/github/Kylian07/PyTorch/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Math Operation**


*   Add, Subtract, Multiply, Divide, Remainder, Exponents
*   Shorthand and uh, Longhand
*   Reassignment





In [1]:
import torch
import numpy as np

In [2]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])

In [3]:
#Addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#Addition Longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
#subtract
tensor_b-tensor_a

tensor([4, 4, 4, 4])

In [7]:
#Subtract Func
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [8]:
#Multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
#multiplication Longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
#Division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
#Division longhand
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#Modulus
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [13]:
#Modulus Longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [14]:
#Exponents Longhand
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
#Another way to write Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
#Reassignment
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a

tensor([1, 2, 3, 4])

In [21]:
#tensor_a=tensor_a+tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([ 6,  8, 10, 12])