<a href="https://colab.research.google.com/github/Kylian07/PyTorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

*   A torch.Tensor a multidimensional matrix contains element of single data
*   Similar to NumPy array but works better in GPU

*   Default datatype is float32










In [1]:
import torch
import numpy as np

# ***List***

In [3]:
my_list=[[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **Numpy**

In [4]:
np1=np.random.rand(3,4)
np1

array([[0.47464516, 0.90654226, 0.43725976, 0.88111094],
       [0.48260567, 0.45022821, 0.94817673, 0.35812964],
       [0.04304311, 0.69039924, 0.6055692 , 0.14886798]])

In [6]:
np1.dtype

dtype('float64')

# **Tensors**

In [10]:
tensor_2d= torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [8]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
#Create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.4746, 0.9065, 0.4373, 0.8811],
        [0.4826, 0.4502, 0.9482, 0.3581],
        [0.0430, 0.6904, 0.6056, 0.1489]], dtype=torch.float64)